/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MealVoucher } from "./MealVoucher";
export type { MockUSDC } from "./MockUSDC";
export type { USDC } from "./USDC";
